### ISSUE TITLE
a vultr api function name parse problem

### ISSUE THREAD

**Issue by apango** [junwen38/vultr-api#1]
The vultr api document have changed the content of the html. So the old way to parse the name of every function is not available anymore.
A new regexp pattern should be applied to match the changes.

suggestion:

    names = (m.group(1) for m in re.finditer(r"<h3>/v1/(.*?)</h3>", html))
    
change to:

    names = (m.group(1) for m in re.finditer(r"<li><a href=\"#.*\">/v1/(.*?)</a></li>", html))

**Comment by junwen38** [comment]
Thank you for reporting. I will fix this issue soon.

**Comment by junwen38** [comment]
I notice you forked this repository and fixed this problem, you can create a pull request to merge your code next time.
